# Generated by Django 3.2.7 on 2022-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registro', models.CharField(max_length=200)),
                ('descripcion_registro', models.CharField(max_length=200)),
            ],
        ),
    ]
